"""Caption style registry. ASS color format: &HAABBGGRR (alpha-blue-green-red)."""

# animation: per_word | sentence | karaoke_pop | typewriter | gradient_pop
STYLES = {
    "word_highlight": {
        "label": "Word highlight",
        "font_size": 82,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H60000000",
        "outline": 3,
        "shadow": 0,
        "bold": 1,
        "alignment": 2,
        "margin_v": 160,
        "border_style": 3,
        "highlight": "&H0000FFFF",
        "dim": "&H80FFFFFF",
        "animation": "per_word",
    },
    "karaoke_pop": {
        "label": "Karaoke pop",
        "font_size": 90,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H00000000",
        "outline": 4,
        "shadow": 1,
        "bold": 1,
        "alignment": 2,
        "margin_v": 200,
        "border_style": 1,
        "highlight": "&H0000FFFF",
        "dim": "&H00FFFFFF",
        "animation": "karaoke_pop",
    },
    "neon_glow": {
        "label": "Neon glow",
        "font_size": 84,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00FF00FF",
        "back_color": "&H00FFFF00",
        "outline": 3,
        "shadow": 4,
        "bold": 1,
        "alignment": 2,
        "margin_v": 200,
        "border_style": 1,
        "highlight": "&H00FFFF00",
        "dim": "&H80FFFFFF",
        "animation": "per_word",
    },
    "bold_yellow": {
        "label": "MrBeast bold",
        "font_size": 110,
        "primary": "&H0000FFFF",
        "outline_color": "&H00000000",
        "back_color": "&H80000000",
        "outline": 6,
        "shadow": 3,
        "bold": 1,
        "alignment": 2,
        "margin_v": 240,
        "border_style": 1,
        "highlight": "&H0000A5FF",
        "dim": "&H0000FFFF",
        "animation": "per_word",
    },
    "bubble": {
        "label": "Bubble",
        "font_size": 70,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00202020",
        "back_color": "&HA0202020",
        "outline": 2,
        "shadow": 0,
        "bold": 0,
        "alignment": 2,
        "margin_v": 140,
        "border_style": 3,
        "highlight": "&H00FFFFFF",
        "dim": "&H80FFFFFF",
        "animation": "sentence",
    },
    "typewriter": {
        "label": "Typewriter",
        "font_size": 72,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H80000000",
        "outline": 2,
        "shadow": 0,
        "bold": 0,
        "alignment": 2,
        "margin_v": 180,
        "border_style": 3,
        "highlight": "&H00FFFFFF",
        "dim": "&H00FFFFFF",
        "animation": "typewriter",
    },
    "gradient_pop": {
        "label": "Gradient pop",
        "font_size": 88,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H00000000",
        "outline": 4,
        "shadow": 2,
        "bold": 1,
        "alignment": 2,
        "margin_v": 200,
        "border_style": 1,
        # cycle palette: red, orange, yellow, lime, cyan
        "palette": ["&H000000FF", "&H000080FF", "&H0000FFFF", "&H0000FF80", "&H00FFFF00"],
        "highlight": "&H0000FFFF",
        "dim": "&H80FFFFFF",
        "animation": "gradient_pop",
    },
    "subtitle_clean": {
        "label": "Clean subtitle",
        "font_size": 52,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H80000000",
        "outline": 2,
        "shadow": 0,
        "bold": 0,
        "alignment": 2,
        "margin_v": 100,
        "border_style": 1,
        "highlight": "&H00FFFFFF",
        "dim": "&H00FFFFFF",
        "animation": "sentence",
    },
    "full_sentence": {
        "label": "Full sentence",
        "font_size": 82,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H60000000",
        "outline": 0,
        "shadow": 0,
        "bold": 1,
        "alignment": 2,
        "margin_v": 160,
        "border_style": 3,
        "highlight": "&H00FFFFFF",
        "dim": "&H00FFFFFF",
        "animation": "sentence",
    },
    "tiktok_native": {
        "label": "TikTok native",
        "font_size": 76,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H00000000",
        "outline": 3,
        "shadow": 2,
        "bold": 1,
        "alignment": 2,
        "margin_v": 220,
        "border_style": 1,
        "highlight": "&H00FFFFFF",
        "dim": "&H80FFFFFF",
        "animation": "sentence",
    },
    "magenta_pop": {
        "label": "Magenta pop",
        "font_size": 90,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H80000000",
        "outline": 4,
        "shadow": 0,
        "bold": 1,
        "alignment": 2,
        "margin_v": 200,
        "border_style": 1,
        "highlight": "&H00C8008C",
        "dim": "&H80FFFFFF",
        "animation": "per_word",
    },
    "cyan_neon": {
        "label": "Cyan neon",
        "font_size": 84,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00FFFF00",
        "back_color": "&H00000000",
        "outline": 4,
        "shadow": 5,
        "bold": 1,
        "alignment": 2,
        "margin_v": 200,
        "border_style": 1,
        "highlight": "&H00FFFF00",
        "dim": "&H80FFFFFF",
        "animation": "per_word",
    },
    "fire_gradient": {
        "label": "Fire gradient",
        "font_size": 92,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H00000000",
        "outline": 4,
        "shadow": 2,
        "bold": 1,
        "alignment": 2,
        "margin_v": 200,
        "border_style": 1,
        # red, orange-red, orange, gold, yellow
        "palette": ["&H000000FF", "&H000040FF", "&H000080FF", "&H0000A0FF", "&H0000FFFF"],
        "highlight": "&H0000A5FF",
        "dim": "&H80FFFFFF",
        "animation": "gradient_pop",
    },
    "spotify_green": {
        "label": "Spotify green",
        "font_size": 80,
        "primary": "&H0060D71E",  # Spotify green (BGR ordering in ASS)
        "outline_color": "&H00000000",
        "back_color": "&HC0000000",
        "outline": 3,
        "shadow": 0,
        "bold": 1,
        "alignment": 2,
        "margin_v": 180,
        "border_style": 3,
        "highlight": "&H0060D71E",
        "dim": "&H80FFFFFF",
        "animation": "sentence",
    },
    "shadow_3d": {
        "label": "3D shadow",
        "font_size": 96,
        "primary": "&H0000FFFF",  # yellow
        "outline_color": "&H00000000",
        # Shadow color (ASS back_color) = vivid orange. Hard-offset shadow
        # with no blur → "stacked 3D" feel that matches CSS preview.
        "back_color": "&H000055D6",  # orange #D65500 (ASS BBGGRR)
        "outline": 0,
        "shadow": 8,
        "bold": 1,
        "alignment": 2,
        "margin_v": 220,
        "border_style": 1,
        "highlight": "&H0000A5FF",
        "dim": "&H0000FFFF",
        "animation": "per_word",
    },
}


def get_style(style_id: str) -> dict:
    return STYLES.get(style_id, STYLES["word_highlight"])


# Animations safe for complex scripts (Devanagari/Tamil etc): no inline color tags per word
COMPLEX_SAFE_ANIMATIONS = {"sentence"}
